//Finlay Braithwaite and Chris Luginbuhl
//Shhhutters - protecting sensitive ears with an sound pressure level-based arduino controlled servomotor.
//Apr 2, 2018
//This code was automatically generated by makecode.adafruit.com by using its graphical programming - which is why it looks a bit strange.

let soundAverage = 0
let servoState = false
let sampleLength = 0
let soundTally = 0
sampleLength = 5000
servoState = false
forever(function () {
    soundTally = 0
    for (let index = 0; index <= sampleLength; index++) {
        soundTally += input.soundLevel()
    }
    soundAverage = soundTally / (sampleLength - 1) //take an average of 1000 soundLevel() samples
    light.graph(soundAverage, 100)                  //use the Circuit Playground Express's onboard neopixels to graph the measured level
    if (soundAverage > 100) {
        pins.A1.servoWrite(0)                       //deploy the shhhutters!
    } else {
        pins.A1.servoWrite(70)                      //retract the shhhhutters.
    }
})